### ISSUE TITLE
getting an error while trying to open the load window

### ISSUE THREAD

**Issue by gerroon** [mbaeuerle/Briss-2.0#20]
Debian Testig x64

```
bin/Briss-2.0                                                                                                                                           [35/86]
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel                                                             
        at at.laborg.briss.BrissGUI.<init>(BrissGUI.java:87)                                                                                       
        at at.laborg.briss.Briss.main(Briss.java:34)                                                                                               
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel                                                                           
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)         
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)       
        ... 2 more                                                                                                                                 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/application/Platform
        at at.laborg.briss.BrissGUI.showOpenFileDialog(BrissGUI.java:291)    
        at at.laborg.briss.BrissGUI.lambda$init$6(BrissGUI.java:192)                                                                               
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632) 
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)                                                                                
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)                                                                                          
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)      
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)                                                                  
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)                                                                  
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)                                                                                         
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)                                                                        
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)                                                                         
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)                                                                                                     
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)                                                                                                             
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)                                                                                                                   
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)                                                                                                                 
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)                                                                                                            
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)                         
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)                         
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                               
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                                                  
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)                                                                  
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)                         
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)                         
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                               
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                                                  
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)                                                                                                                
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                                                     
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                                        
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)                                                                                     
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                                                                                                 
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                                 
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)                                                                                                         
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform                       
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)                                                                                            
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)                                                                                         
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                    
        ... 37 more                            
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/application/Platform                                                                                            
        at at.laborg.briss.BrissGUI.showOpenFileDialog(BrissGUI.java:291)                                                                                                                     
        at at.laborg.briss.BrissGUI.lambda$init$6(BrissGUI.java:192)                           
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)             

```

**Comment by cleydyr** [comment]
Hey, @gerroon . I'd like to drop in and ask what's the JDK version that you are using.

**Comment by cleydyr** [comment]
Related question on SOF: [What does “Exception in thread ”main“ java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel” mean and how do I fix it?](https://stackoverflow.com/questions/55250610/what-does-exception-in-thread-main-java-lang-noclassdeffounderror-javafx-emb)

**Comment by raydac** [comment]
JDK doesn't include javafx by default anymore so that it should be installed separately, I make [releases  with embedded LibericaOpenJDK](https://github.com/raydac/Briss-2.0/releases)

**Comment by gerroon** [comment]
I use

```
openjdk 14-ea 2020-03-17
OpenJDK Runtime Environment (build 14-ea+32-Debian-1)
OpenJDK 64-Bit Server VM (build 14-ea+32-Debian-1, mixed mode, sharing)

```

**Comment by mbaeuerle** [comment]
It looks like @raydac is right and the component was moved out of the JDK core for newer Java versions. 
The purpose of this dependency was to use the JavaFX FileChooser component as the Swing/AWT versions don't use the operating systems native ones and therefore IMO don't look very nice.

**Comment by mbaeuerle** [comment]
I just created a new version: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-2 could you check if it works now on your machine?

**Comment by gerroon** [comment]
It seems to work, thanks for the release

**Comment by mbaeuerle** [comment]
@gerroon glad it worked!
