### ISSUE TITLE
How do I install Briss-2.0? I don't see a gradlew folder in the Briss2.0 extracted zip

### ISSUE THREAD

**Issue by hub2git** [mbaeuerle/Briss-2.0#21]
Here's what I've tried to do so far

1. Go to https://github.com/mbaeuerle/Briss-2.0
2. Press the green box that says  "Clone or Download"
3. Choose "Download ZIP"
4. Extract the ZIP onto the Windows computer.

https://github.com/mbaeuerle/Briss-2.0#build-instructions says I have to `./gradlew distZip`. But I don't see  a gradlew folder in the Briss-2.0 extracted files.

**Comment by cleydyr** [comment]
`./gradlew` doesn't refer to a folder, but to an executable file which is included in the downloaded zip. Did you try using a terminal of sorts to run the command?

**Comment by mbaeuerle** [comment]
@hub2git I guess you just want to use Briss 2.0? Then you can download the alpha release here: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha

The build instructions are only needed to compile Briss from the source code.

**Comment by hub2git** [comment]
`yes, i just want to use Briss 2.0. I downloaded Briss-2.0.zip
<https://github.com/mbaeuerle/Briss-2.0/releases/download/v2.0-alpha/Briss-2.0.zip>
(
https://github.com/mbaeuerle/Briss-2.0/releases/download/v2.0-alpha/Briss-2.0.zip)
to a Windows computer at the computer lab. I then extracted the zip. I open
up Command Prompt and execute the Briss-2.0.bat.

I see this:
\Briss-2.0.bat
Exception in thread "main" java.lang.UnsupportedClassVersionError:
at/laborg/briss/Briss : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by raydac** [comment]
@hub2git 
you can try my versions https://github.com/raydac/Briss-2.0/releases/tag/2.0-SNAPSHOT

**Comment by mbaeuerle** [comment]
@hub2git which version of Java do you have installed?
This error normally shows up when you are using a version of Java which is lower than Java 8.

**Comment by hub2git** [comment]
i'm not a real techie person and i'm afraid of messing with my computer.
Plus, it appears that briss2.0 doesn't really add any cropping features to
briss 0.9. so i might just stick with briss 0.9.

**Comment by mbaeuerle** [comment]
@hub2git yes you are right, you are not new features in Briss 2.0, it is currently just a GUI overhaul.
Nevertheless I just created a new version, you could give it a try: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-2

**Comment by hub2git** [comment]
On the school computer (Windows 10), it doesn't work. Maybe because I don't have admin privileges.

**Comment by mbaeuerle** [comment]
@hub2git admin privileges should not be needed to run Briss. Could you please check which version of Java you have installed?

**Comment by nec0** [comment]
same problem with me

java installed: jdk-8u251-windows-x64

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: at/laborg/briss/Briss has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
