### ISSUE TITLE
Loading a new PDF after opening one leads to NPE and empty screen

### ISSUE THREAD

**Issue by mbaeuerle** [mbaeuerle/Briss-2.0#24]
1. Load any PDF
2. Go to `File`->`Load` and load any PDF
3. Crop window stays empty and following exception is showing up in the console:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at at.laborg.briss.BrissGUI.copyCropsToClusters(BrissGUI.java:661)
	at at.laborg.briss.BrissGUI.updateWorkingSet(BrissGUI.java:649)
	at at.laborg.briss.BrissGUI.setStateAfterClusteringFinished(BrissGUI.java:621)
	at at.laborg.briss.BrissGUI$ClusterPagesTask.done(BrissGUI.java:682)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by mbaeuerle** [comment]
Could not reproduce this behavior any longer, therefore closing this.
