### ISSUE TITLE
V2-alpha 3 exceptions in Command prompt

### ISSUE THREAD

**Issue by cksachdev** [mbaeuerle/Briss-2.0#49]
Operating System: Windows 10
JDK: openjdk 11
JDK used: https://docs.microsoft.com/en-us/java/openjdk/download#openjdk-11
![image](https://user-images.githubusercontent.com/37770/183638373-cdccba55-eefe-4b77-99fb-68621a88f412.png)

Let me know if there are any other system logs required.

**Comment by cksachdev** [comment]
Getting few more exceptions:
![image](https://user-images.githubusercontent.com/37770/183639335-dc41d496-e8a4-4601-b25d-0011124b84e9.png)

I am trying to use this [pdf](http://kannadapraadhikaara.karnataka.gov.in/storage/pdf-files/%E0%B2%95%E0%B2%A8%E0%B3%8D%E0%B2%A8%E0%B2%A1%20%E0%B2%B8%E0%B3%8D%E0%B2%B5%E0%B2%AF%E0%B2%82%20%E0%B2%AD%E0%B3%8B%E0%B2%A6%E0%B2%A8%E0%B3%86%20(%E0%B2%87%E0%B2%82%E0%B2%97%E0%B3%8D%E0%B2%B2%E0%B3%80%E0%B2%B7%E0%B3%8D%20-%20%E0%B2%95%E0%B2%A8%E0%B3%8D%E0%B2%A8%E0%B2%A1).pdf) but couldn't get it to split in a sequence. Configured the pages as shown in screenshot below:

![image](https://user-images.githubusercontent.com/37770/183639665-0dfcfe8a-a487-4a5c-8753-1613942a28ae.png)

**Comment by cleydyr** [comment]
Hey, @cksachdev .

What is the Windows 11 architecture that you're using. Is it arm64?

**Comment by cksachdev** [comment]
No, its intel x86.

**Comment by VladimirAlexiev** [comment]
@cleydyr I get the same exception as @cksachdev, here it is as text:
```
InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:251)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:267)
        at at.laborg.briss.BrissGUI.<init>(BrissGUI.java:123)
        at at.laborg.briss.Briss.main(Briss.java:34)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:251)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:267)
        at at.laborg.briss.BrissGUI.<init>(BrissGUI.java:123)
        at at.laborg.briss.Briss.main(Briss.java:34)
```

System configuration:
```
# systeminfo
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       LENOVO
System Model:              21A90007BM
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 141 Stepping 1 GenuineIntel ~2688 Mhz
BIOS Version:              LENOVO N38ET29W (1.10 ), 8/3/2021

# java -version
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9)
OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode, sharing)
```

**Comment by cleydyr** [comment]
Hey, @VladimirAlexiev, thank you for the detailed information. I could reproduce the issue and get rid of it by adding the javafx dependencies.

I'll send a PR soon.

**Comment by cleydyr** [comment]
Hey, @cksachdev and @VladimirAlexiev .

I've released a new version of Briss 2.0 alpha. Can you give it a try and see if the issue this issue is solved there?
